/* eslint-disable prettier/prettier */
const items = [
    {
      id: '1',
      name: 'Pizza',
      price: '180.000',
      image: require('../components/itemdata/Foods/pizza5.jpg'),
    },
    {
      id: '2',
      name: 'Burgers',
      price: '40.000',
      image: require('../components/itemdata/Foods/burger1.jpg'),
    },
    {
      id: '3',
      name: 'Spaghetti',
      price: '50.000',
      image: require('../components/itemdata/Foods/spa2.jpg'),
    },
    {
      id: '4',
      name: 'Sushi',
      price: '120.000',
      image: require('../components/itemdata/Foods/sushi2.jpg'),
    },
    {
      id: '5',
      name: 'Sandwich',
      price: '25.000',
      image: require('../components/itemdata/Foods/sand1.jpg'),
    },
    {
        id: '6',
        name: 'Beef Steak',
        price: '320.000',
        image: require('../components/itemdata/Items/beef.jpg'),
    },
    {
        id: '7',
        name: 'Bread',
        price: '20.000',
        image: require('../components/itemdata/Items/bread.jpg'),
    },
    {
        id: '8',
        name: 'BBQ Chicken',
        price: '250.000',
        image: require('../components/itemdata/Items/chicken1.jpg'),
    },
    {
        id: '9',
        name: 'Pad Thai',
        price: '42.000',
        image: require('../components/itemdata/Items/pad.jpg'),
    },
    {
        id: '10',
        name: 'Fried Rice',
        price: '55.000',
        image: require('../components/itemdata/Items/rice.jpg'),
    },
    {
        id: '11',
        name: 'Salad Vegetables',
        price: '45.000',
        image: require('../components/itemdata/Items/salad5.jpg'),
    },
    {
        id: '12',
        name: 'Shrimp Yum',
        price: '48.000',
        image: require('../components/itemdata/Items/tomyum.jpg'),
    },
    {
        id: '13',
        name: 'Sandwich Premium',
        price: '55.000',
        image: require('../components/itemdata/Foods/sand2.jpg'),
    },
    {
        id: '14',
        name: 'Roasted duck',
        price: '320.000',
        image: require('../components/itemdata/Items/vit.jpg'),
    },
    {
        id: '15',
        name: 'Campucino',
        price: '40.000',
        image: require('../components/itemdata/Items/campucino.jpg'),
    },
    {
        id: '16',
        name: 'Coffee',
        price: '25.000',
        image: require('../components/itemdata/Items/coffee.jpg'),
    },
    {
        id: '17',
        name: 'Sting',
        price: '20.000',
        image: require('../components/itemdata/Items/sting1.jpg'),
    },
    {
        id: '18',
        name: 'Coca Cola',
        price: '22.000',
        image: require('../components/itemdata/Items/coca1.jpg'),
    },{
        id: '19',
        name: 'Pepsi',
        price: '25.000',
        image: require('../components/itemdata/Items/pepsi.jpg'),
    },
    {
        id: '20',
        name: 'Strawberry cake',
        price: '232.000',
        image: require('../components/itemdata/Items/cake2.jpg'),
    },
    {
        id: '21',
        name: 'Peach Soju',
        price: '42.000',
        image: require('../components/itemdata/Items/soju1.jpg'),
    },
    {
        id: '22',
        name: 'Strawberry Soju',
        price: '52.000',
        image: require('../components/itemdata/Items/soju2.jpg'),
    },
    {
        id: '23',
        name: 'Reservado',
        price: '330.000',
        image: require('../components/itemdata/Items/reservado.jpg'),
    },
    {
        id: '24',
        name: 'Malibu',
        price: '530.000',
        image: require('../components/itemdata/Items/ruou1.jpg'),
    },
    {
        id: '25',
        name: 'Smirnoff',
        price: '250.000',
        image: require('../components/itemdata/Items/strawbery.jpg'),
    },
    {
        id: '26',
        name: 'Vodka',
        price: '2.500.000',
        image: require('../components/itemdata/Items/vodka.jpg'),
    },
    {
        id: '27',
        name: 'Milk Tea',
        price: '30.000',
        image: require('../components/itemdata/Items/gongcha.jpg'),
    },
    {
        id: '28',
        name: 'Strawberry mik tea',
        price: '35.000',
        image: require('../components/itemdata/Items/gongcha2.jpg'),
    },
    {
        id: '29',
        name: 'Matcha milk tea',
        price: '37.000',
        image: require('../components/itemdata/Items/gongcha3.jpg'),
    },
    {
        id: '30',
        name: 'Blue milk tea',
        price: '240000',
        image: require('../components/itemdata/Items/gongcha4.jpg'),
    },
  ];
  
  export default items;